/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthorModel model module.
 * @module model/AuthorModel
 * @version 1.0
 */
export class AuthorModel {
  /**
   * Constructs a new <code>AuthorModel</code>.
   * @alias module:model/AuthorModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthorModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorModel} obj Optional instance to populate.
   * @return {module:model/AuthorModel} The populated <code>AuthorModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthorModel();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
AuthorModel.prototype.name = undefined;

/**
 * @member {Number} id
 */
AuthorModel.prototype.id = undefined;

