/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UserModel} from './UserModel';

/**
 * The ChannelMemberModel model module.
 * @module model/ChannelMemberModel
 * @version 1.0
 */
export class ChannelMemberModel {
  /**
   * Constructs a new <code>ChannelMemberModel</code>.
   * @alias module:model/ChannelMemberModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChannelMemberModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelMemberModel} obj Optional instance to populate.
   * @return {module:model/ChannelMemberModel} The populated <code>ChannelMemberModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChannelMemberModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('isAdmin'))
        obj.isAdmin = ApiClient.convertToType(data['isAdmin'], 'Boolean');
      if (data.hasOwnProperty('lastSeenMessage'))
        obj.lastSeenMessage = ApiClient.convertToType(data['lastSeenMessage'], 'Number');
      if (data.hasOwnProperty('nick'))
        obj.nick = ApiClient.convertToType(data['nick'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = UserModel.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ChannelMemberModel.prototype.id = undefined;

/**
 * @member {Boolean} isAdmin
 */
ChannelMemberModel.prototype.isAdmin = undefined;

/**
 * @member {Number} lastSeenMessage
 */
ChannelMemberModel.prototype.lastSeenMessage = undefined;

/**
 * @member {String} nick
 */
ChannelMemberModel.prototype.nick = undefined;

/**
 * @member {module:model/UserModel} user
 */
ChannelMemberModel.prototype.user = undefined;

