/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChannelMemberModel} from './ChannelMemberModel';

/**
 * The ChannelModel model module.
 * @module model/ChannelModel
 * @version 1.0
 */
export class ChannelModel {
  /**
   * Constructs a new <code>ChannelModel</code>.
   * @alias module:model/ChannelModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChannelModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChannelModel} obj Optional instance to populate.
   * @return {module:model/ChannelModel} The populated <code>ChannelModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChannelModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('members'))
        obj.members = ApiClient.convertToType(data['members'], [ChannelMemberModel]);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ChannelModel.prototype.id = undefined;

/**
 * @member {Array.<module:model/ChannelMemberModel>} members
 */
ChannelModel.prototype.members = undefined;

/**
 * @member {String} title
 */
ChannelModel.prototype.title = undefined;

