/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FilesUploadBody model module.
 * @module model/FilesUploadBody
 * @version 1.0
 */
export class FilesUploadBody {
  /**
   * Constructs a new <code>FilesUploadBody</code>.
   * @alias module:model/FilesUploadBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FilesUploadBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilesUploadBody} obj Optional instance to populate.
   * @return {module:model/FilesUploadBody} The populated <code>FilesUploadBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FilesUploadBody();
      if (data.hasOwnProperty('files'))
        obj.files = ApiClient.convertToType(data['files'], ['Blob']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Blob>} files
 */
FilesUploadBody.prototype.files = undefined;

