/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UserModel} from './UserModel';

/**
 * The FriendshipModel model module.
 * @module model/FriendshipModel
 * @version 1.0
 */
export class FriendshipModel {
  /**
   * Constructs a new <code>FriendshipModel</code>.
   * @alias module:model/FriendshipModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FriendshipModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FriendshipModel} obj Optional instance to populate.
   * @return {module:model/FriendshipModel} The populated <code>FriendshipModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FriendshipModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('sender'))
        obj.sender = UserModel.constructFromObject(data['sender']);
      if (data.hasOwnProperty('recepient'))
        obj.recepient = UserModel.constructFromObject(data['recepient']);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
FriendshipModel.prototype.id = undefined;

/**
 * @member {module:model/UserModel} sender
 */
FriendshipModel.prototype.sender = undefined;

/**
 * @member {module:model/UserModel} recepient
 */
FriendshipModel.prototype.recepient = undefined;

/**
 * @member {Boolean} status
 */
FriendshipModel.prototype.status = undefined;

