/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductModel} from './ProductModel';
import {UserModel} from './UserModel';

/**
 * The GameActivityModel model module.
 * @module model/GameActivityModel
 * @version 1.0
 */
export class GameActivityModel {
  /**
   * Constructs a new <code>GameActivityModel</code>.
   * @alias module:model/GameActivityModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameActivityModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameActivityModel} obj Optional instance to populate.
   * @return {module:model/GameActivityModel} The populated <code>GameActivityModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameActivityModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('product'))
        obj.product = ProductModel.constructFromObject(data['product']);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('user'))
        obj.user = UserModel.constructFromObject(data['user']);
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
GameActivityModel.prototype.id = undefined;

/**
 * @member {Date} startDate
 */
GameActivityModel.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
GameActivityModel.prototype.endDate = undefined;

/**
 * @member {module:model/ProductModel} product
 */
GameActivityModel.prototype.product = undefined;

/**
 * @member {Number} productId
 */
GameActivityModel.prototype.productId = undefined;

/**
 * @member {module:model/UserModel} user
 */
GameActivityModel.prototype.user = undefined;

/**
 * @member {Number} userId
 */
GameActivityModel.prototype.userId = undefined;

