/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OperatingSystemEnum} from './OperatingSystemEnum';
import {ProductModel} from './ProductModel';

/**
 * The PackageModel model module.
 * @module model/PackageModel
 * @version 1.0
 */
export class PackageModel {
  /**
   * Constructs a new <code>PackageModel</code>.
   * @alias module:model/PackageModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PackageModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageModel} obj Optional instance to populate.
   * @return {module:model/PackageModel} The populated <code>PackageModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PackageModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('product'))
        obj.product = ProductModel.constructFromObject(data['product']);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('supportedOperatingSystems'))
        obj.supportedOperatingSystems = OperatingSystemEnum.constructFromObject(data['supportedOperatingSystems']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
PackageModel.prototype.id = undefined;

/**
 * @member {Date} _date
 */
PackageModel.prototype._date = undefined;

/**
 * @member {module:model/ProductModel} product
 */
PackageModel.prototype.product = undefined;

/**
 * @member {Number} productId
 */
PackageModel.prototype.productId = undefined;

/**
 * @member {String} description
 */
PackageModel.prototype.description = undefined;

/**
 * @member {module:model/OperatingSystemEnum} supportedOperatingSystems
 */
PackageModel.prototype.supportedOperatingSystems = undefined;

