/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ProductModel} from './ProductModel';
import {UserModel} from './UserModel';

/**
 * The PurchaseModel model module.
 * @module model/PurchaseModel
 * @version 1.0
 */
export class PurchaseModel {
  /**
   * Constructs a new <code>PurchaseModel</code>.
   * @alias module:model/PurchaseModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PurchaseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PurchaseModel} obj Optional instance to populate.
   * @return {module:model/PurchaseModel} The populated <code>PurchaseModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PurchaseModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('product'))
        obj.product = ProductModel.constructFromObject(data['product']);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('user'))
        obj.user = UserModel.constructFromObject(data['user']);
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
PurchaseModel.prototype.id = undefined;

/**
 * @member {Date} _date
 */
PurchaseModel.prototype._date = undefined;

/**
 * @member {module:model/ProductModel} product
 */
PurchaseModel.prototype.product = undefined;

/**
 * @member {Number} productId
 */
PurchaseModel.prototype.productId = undefined;

/**
 * @member {module:model/UserModel} user
 */
PurchaseModel.prototype.user = undefined;

/**
 * @member {Number} userId
 */
PurchaseModel.prototype.userId = undefined;

/**
 * @member {Number} value
 */
PurchaseModel.prototype.value = undefined;

