/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RatesData model module.
 * @module model/RatesData
 * @version 1.0
 */
export class RatesData {
  /**
   * Constructs a new <code>RatesData</code>.
   * @alias module:model/RatesData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RatesData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatesData} obj Optional instance to populate.
   * @return {module:model/RatesData} The populated <code>RatesData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RatesData();
      if (data.hasOwnProperty('avg'))
        obj.avg = ApiClient.convertToType(data['avg'], 'Number');
      if (data.hasOwnProperty('rateCounts'))
        obj.rateCounts = ApiClient.convertToType(data['rateCounts'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Number} avg
 */
RatesData.prototype.avg = undefined;

/**
 * @member {Array.<Number>} rateCounts
 */
RatesData.prototype.rateCounts = undefined;

