/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.46
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TagModel model module.
 * @module model/TagModel
 * @version 1.0
 */
export class TagModel {
  /**
   * Constructs a new <code>TagModel</code>.
   * @alias module:model/TagModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TagModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagModel} obj Optional instance to populate.
   * @return {module:model/TagModel} The populated <code>TagModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('tag'))
        obj.tag = ApiClient.convertToType(data['tag'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
TagModel.prototype.id = undefined;

/**
 * @member {String} tag
 */
TagModel.prototype.tag = undefined;

