/*
 * ndibAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.48
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserImagesModel model module.
 * @module model/UserImagesModel
 * @version 1.0
 */
export class UserImagesModel {
  /**
   * Constructs a new <code>UserImagesModel</code>.
   * @alias module:model/UserImagesModel
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserImagesModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserImagesModel} obj Optional instance to populate.
   * @return {module:model/UserImagesModel} The populated <code>UserImagesModel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserImagesModel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('profileImageBase64'))
        obj.profileImageBase64 = ApiClient.convertToType(data['profileImageBase64'], 'String');
      if (data.hasOwnProperty('bckgroundImageBase64'))
        obj.bckgroundImageBase64 = ApiClient.convertToType(data['bckgroundImageBase64'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
UserImagesModel.prototype.id = undefined;

/**
 * @member {String} profileImageBase64
 */
UserImagesModel.prototype.profileImageBase64 = undefined;

/**
 * @member {String} bckgroundImageBase64
 */
UserImagesModel.prototype.bckgroundImageBase64 = undefined;

